name: SatanicDesign
version: '${project.version}'
main: org.mrdarkimc.SatanicDesign
description: Плагин на редизайн.
api-version: '1.21'
author: MrDarkiMC
website: https://t.me/doomgxard
depend:
  - PlaceholderAPI
commands:
  sutil:
    usage: /design help
  backrtp:
    usage: /design help